Avoid recommending outdated PPA for now
racket/racket-lang-org pull request #318
Opened 2024-08-14 03:34 UTC by LiberalArtist

While [replying to a Discourse post](https://racket.discourse.group/t/flomat-install-under-linux-can-not-find-libfortran/3088/13), I noticed that the Ubuntu PPA is still on Racket 8.6. Meanwhile, Ubuntu [23.10 (Mantic Minotaur)](https://packages.ubuntu.com/mantic/racket) has Racket 8.7, Ubuntu [24.04 LTS (Noble Numbat)](https://packages.ubuntu.com/noble/racket) has Racket 8.10, and the forthcoming [24.10 (Oracular Oriole)](https://packages.ubuntu.com/oracular/racket) currently has Racket 8.12. ([Debian Testing](https://packages.debian.org/trixie/racket) has Racket 8.13, so Ubuntu could pull further updates before their release.) The Ubuntu 24.04.1 LTS point release is scheduled for this month, at which point Ubuntu will begin prompting users of 22.04 LTS (Jammy Jellyfish) to upgrade.

Since even users following LTS Ubuntu will get a newer version of Racket from the distro apt repository than by using the PPA, I think it would be confusing to continue recommending the PPA until it is updated. I haven't tested this, but, depending on what apt configuration PPAs generate, I'm concerned that enabling the PPA might even hide the newer Racket available from the distro repository.

2024-08-14 06:06 UTC, sorawee requested changes
I think this is a good idea, but could you also comment out `showWhen('linux_ppa', platform.search(/linux/) >= 0);` below so that JS doesn't error out when it can't find the span? Thanks!

2024-08-17 00:16 UTC, LiberalArtist commented
> could you also comment out `showWhen('linux_ppa', platform.search(/linux/) >= 0);` below so that JS doesn't error

Thanks, I'd missed that! I've pushed a revised commit.

2024-08-20 17:24 UTC, sorawee commented
Whoops. I missed this. LGTM!

2024-08-20 17:24 UTC, merged

2024-08-20 21:31 UTC, sorawee commented
On the second look, it definitely could not have looked good to me 😂 . I definitely have been too tired...

2024-08-20 21:54 UTC, LiberalArtist commented
Apparently I `git commit --amend`ed without actually staging my amended changes &hellip; Thanks for fixing it, @sorawee!